### ISSUE TITLE
GPIO: Reading RI_GPIO_ID_UNUSED pin asserts.

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.drivers.c#140]
Error code should be returned instead, i.e. INVALID_PARAM.

**Comment by niksiboxi** [comment]
Calling `rd_status_t ri_i2c_init (const ri_i2c_init_config_t * config)` when `ri_gpio_id_t bus_pwr` is set as `RB_I2C_BUS_POWER_PIN ` aka `RB_PIN_UNUSED`, creates `ASSERTION FAILED`

**Comment by ojousima** [comment]
Return RD_SUCCESS on ID_UNUSED, that allows e.g. unused power pins to work with current code

**Comment by ojousima** [comment]
This was fixed in #199
